// Shared constants used across background, popup, and options scripts.
// Imported as an ES module (manifest declares the service worker as type "module",
// and popup/options load this file as a <script type="module">).

export const PHASE = {
  WORK: "work",
  REST: "rest",
  LONG_BREAK: "longBreak",
};

export const STATUS = {
  IDLE: "idle",
  RUNNING: "running",
  PAUSED: "paused",
};

export const BLOCK_MODE = {
  OFF: "off",
  BLACKLIST: "blacklist",
  WHITELIST: "whitelist",
};

export const STORAGE_KEYS = {
  SETTINGS: "settings",
  TIMER_STATE: "timerState",
  THEME: "theme",
  STATS: "stats",
  TASKS: "tasks",
};

// Task list shown in the popup and edited on the options page. Each entry is
// { id: <string>, text: <string>, done: <boolean> }. Kept in chrome.storage.local
// like everything else — never leaves the device.
export const DEFAULT_TASKS = [];

// Windows the popup's "total minutes focused" counter can add up over.
// 'all' means "everything since the user last hit Reset in settings".
export const STATS_WINDOW = {
  HOUR: "hour",
  DAY: "day",
  WEEK: "week",
  MONTH: "month",
  ALL: "all",
};

// 'system' follows the OS/browser preference; 'light'/'dark' are explicit
// manual overrides set via the theme toggle button on each page.
export const THEME_OPTIONS = ["system", "light", "dark"];
export const DEFAULT_THEME = "system";

export const DEFAULT_SETTINGS = {
  // Restrictive mode: once a focus session is running, timer/blocking settings
  // freeze, the timer can't be skipped, and it can only be reset while paused
  // after a typed confirmation. Blocked pages also lose their "Continue anyway".
  restrictiveMode: false,
  workMinutes: 25,
  restMinutes: 5,
  cyclesBeforeLongBreak: 4,
  longBreakMinutes: 15,
  warningEnabled: true,
  warningSeconds: 30,
  soundOnEnd: true,
  soundOnWarning: true,
  badgeCountdown: true,
  statsWindow: STATS_WINDOW.DAY,
  // Idle detection: pause automatically after this many minutes of no mouse/
  // keyboard activity (or the screen locking), so walking away doesn't burn
  // through a session or inflate your focus total. Off by default since it's
  // a behavior change, not just a preference.
  idleEnabled: false,
  idleMinutes: 5,
  // Only consulted while idleEnabled is on: resume on its own the moment
  // you're active again, versus staying paused until you hit Resume yourself.
  idleAutoResume: true,
  blockMode: BLOCK_MODE.OFF,
  // Blacklist and whitelist keep entirely separate lists — switching modes
  // never carries entries from one into the other.
  blacklist: [],
  whitelist: [],
};

export const DEFAULT_STATS = {
  // Each completed (or partially completed) focus stretch is logged here as
  // { end: <epoch ms>, ms: <focused milliseconds> }. The popup sums the entries
  // that fall inside the chosen window.
  focusLog: [],
  // Entries that ended before this are ignored — bumped to "now" when the user
  // clicks "Reset focus total" in settings.
  resetAt: 0,
};

// Pre-built groups of sites offered on the options page as quick-add "folders".
// Each folder has a whole-folder checkbox plus a checkbox per site; toggling
// either just adds/removes the (already-normalized) hostnames from the current
// mode's list, so the blocking engine never has to know folders exist.
export const SITE_FOLDERS = {
  [BLOCK_MODE.BLACKLIST]: [
    {
      name: "Social Media",
      sites: [
        "facebook.com",
        "instagram.com",
        "twitter.com",
        "x.com",
        "tiktok.com",
        "reddit.com",
        "snapchat.com",
        "pinterest.com",
        "linkedin.com",
        "tumblr.com",
        "threads.net",
        "threads.com",
        "mastodon.social",
        "bsky.app",
        "discord.com",
        "whatsapp.com",
        "web.whatsapp.com",
        "telegram.org",
        "web.telegram.org",
        "messenger.com",
        "vk.com",
        "weibo.com",
        "quora.com",
        "nextdoor.com",
        "meetup.com",
        "flickr.com",
        "myspace.com",
        "kik.com",
        "viber.com",
        "line.me",
        "wechat.com",
        "qq.com",
        "douyin.com",
        "xiaohongshu.com",
        "bereal.com",
        "clubhouse.com",
        "gettr.com",
        "truthsocial.com",
        "parler.com",
        "mewe.com",
        "9gag.com",
        "imgur.com",
        "tinder.com",
        "bumble.com",
        "hinge.co",
        "okcupid.com",
        "grindr.com",
        "tagged.com",
        "ask.fm",
      ],
    },
    {
      name: "Entertainment",
      sites: [
        "youtube.com",
        "netflix.com",
        "hulu.com",
        "disneyplus.com",
        "hbomax.com",
        "max.com",
        "primevideo.com",
        "peacocktv.com",
        "paramountplus.com",
        "crunchyroll.com",
        "funimation.com",
        "tv.apple.com",
        "tubitv.com",
        "pluto.tv",
        "sling.com",
        "fubo.tv",
        "discoveryplus.com",
        "starz.com",
        "showtime.com",
        "mubi.com",
        "vudu.com",
        "twitch.tv",
        "kick.com",
        "vimeo.com",
        "dailymotion.com",
        "rumble.com",
        "ted.com",
        "spotify.com",
        "music.apple.com",
        "pandora.com",
        "soundcloud.com",
        "tidal.com",
        "deezer.com",
        "iheart.com",
        "audible.com",
        "bandcamp.com",
        "mixcloud.com",
        "last.fm",
        "imdb.com",
        "rottentomatoes.com",
        "metacritic.com",
        "fandango.com",
        "giphy.com",
        "tenor.com",
        "buzzfeed.com",
        "boredpanda.com",
        "theonion.com",
        "espn.com",
        "bleacherreport.com",
        "nba.com",
        "nfl.com",
        "mlb.com",
        "nhl.com",
        "foxsports.com",
        "cbssports.com",
        "dazn.com",
        "wwe.com",
        "ufc.com",
      ],
    },
    {
      name: "Shopping",
      sites: [
        "amazon.com",
        "ebay.com",
        "walmart.com",
        "target.com",
        "bestbuy.com",
        "etsy.com",
        "aliexpress.com",
        "alibaba.com",
        "temu.com",
        "shein.com",
        "wish.com",
        "wayfair.com",
        "overstock.com",
        "homedepot.com",
        "lowes.com",
        "costco.com",
        "samsclub.com",
        "kohls.com",
        "macys.com",
        "nordstrom.com",
        "nordstromrack.com",
        "jcpenney.com",
        "dillards.com",
        "gap.com",
        "oldnavy.com",
        "bananarepublic.com",
        "hm.com",
        "zara.com",
        "uniqlo.com",
        "asos.com",
        "forever21.com",
        "urbanoutfitters.com",
        "anthropologie.com",
        "nike.com",
        "adidas.com",
        "footlocker.com",
        "lululemon.com",
        "gymshark.com",
        "sephora.com",
        "ulta.com",
        "ikea.com",
        "crateandbarrel.com",
        "potterybarn.com",
        "chewy.com",
        "petco.com",
        "petsmart.com",
        "newegg.com",
        "bhphotovideo.com",
        "microcenter.com",
        "poshmark.com",
        "mercari.com",
        "depop.com",
        "therealreal.com",
        "stockx.com",
        "goat.com",
        "craigslist.org",
        "offerup.com",
        "rakuten.com",
        "groupon.com",
        "qvc.com",
        "zappos.com",
      ],
    },
    {
      name: "Games",
      sites: [
        "steampowered.com",
        "store.steampowered.com",
        "steamcommunity.com",
        "steamdb.info",
        "epicgames.com",
        "gog.com",
        "itch.io",
        "humblebundle.com",
        "origin.com",
        "ea.com",
        "ubisoft.com",
        "ubisoftconnect.com",
        "battle.net",
        "blizzard.com",
        "xbox.com",
        "playstation.com",
        "nintendo.com",
        "ign.com",
        "gamespot.com",
        "kotaku.com",
        "polygon.com",
        "pcgamer.com",
        "rockpapershotgun.com",
        "eurogamer.net",
        "gamesradar.com",
        "destructoid.com",
        "gamefaqs.gamespot.com",
        "nexusmods.com",
        "curseforge.com",
        "modrinth.com",
        "roblox.com",
        "minecraft.net",
        "fortnite.com",
        "leagueoflegends.com",
        "riotgames.com",
        "valorant.com",
        "pubg.com",
        "supercell.com",
        "king.com",
        "chess.com",
        "lichess.org",
        "miniclip.com",
        "poki.com",
        "crazygames.com",
        "coolmathgames.com",
        "addictinggames.com",
        "kongregate.com",
        "armorgames.com",
        "newgrounds.com",
        "y8.com",
        "agar.io",
        "slither.io",
        "krunker.io",
        "skribbl.io",
        "geoguessr.com",
        "jackbox.tv",
      ],
    },
    {
      name: "News",
      sites: [
        "cnn.com",
        "foxnews.com",
        "msnbc.com",
        "nytimes.com",
        "washingtonpost.com",
        "wsj.com",
        "usatoday.com",
        "nbcnews.com",
        "abcnews.go.com",
        "cbsnews.com",
        "bbc.com",
        "bbc.co.uk",
        "theguardian.com",
        "reuters.com",
        "apnews.com",
        "npr.org",
        "bloomberg.com",
        "forbes.com",
        "businessinsider.com",
        "cnbc.com",
        "marketwatch.com",
        "huffpost.com",
        "politico.com",
        "thehill.com",
        "axios.com",
        "vox.com",
        "slate.com",
        "salon.com",
        "theatlantic.com",
        "newyorker.com",
        "time.com",
        "newsweek.com",
        "economist.com",
        "ft.com",
        "aljazeera.com",
        "dw.com",
        "france24.com",
        "nypost.com",
        "dailymail.co.uk",
        "mirror.co.uk",
        "thesun.co.uk",
        "breitbart.com",
        "dailywire.com",
        "newsmax.com",
        "theblaze.com",
        "motherjones.com",
        "thedailybeast.com",
        "drudgereport.com",
        "vice.com",
        "propublica.org",
        "latimes.com",
        "chicagotribune.com",
        "nydailynews.com",
        "sfgate.com",
        "news.google.com",
        "news.yahoo.com",
      ],
    },
  ],
  [BLOCK_MODE.WHITELIST]: [
    {
      name: "Classroom Websites",
      sites: [
        "classroom.google.com",
        "instructure.com",
        "schoology.com",
        "clever.com",
        "blackboard.com",
        "canvas.net",
        "edmodo.com",
        "nearpod.com",
        "kahoot.it",
        "quizlet.com",
        "quizizz.com",
        "desmos.com",
        "powerschool.com",
        "classlink.com",
        "seesaw.com",
        "flip.com",
        "padlet.com",
        "newsela.com",
        "commonlit.org",
        "ixl.com",
      ],
    },
    {
      name: "Research Tools",
      sites: [
        "wikipedia.org",
        "khanacademy.org",
        "scholar.google.com",
        "docs.google.com",
        "drive.google.com",
        "jstor.org",
        "britannica.com",
        "sparknotes.com",
        "wolframalpha.com",
        "dictionary.com",
        "merriam-webster.com",
        "thesaurus.com",
        "purdue.edu",
        "owl.purdue.edu",
        "archive.org",
        "gutenberg.org",
        "arxiv.org",
        "pubmed.ncbi.nlm.nih.gov",
        "ncbi.nlm.nih.gov",
        "sciencedirect.com",
      ],
    },
  ],
};

export const DEFAULT_TIMER_STATE = {
  status: STATUS.IDLE,
  phase: PHASE.WORK,
  cycleCount: 0, // number of work sessions completed since the last long break
  phaseEndTime: null, // epoch ms; null when idle/paused
  remainingMsWhenPaused: null,
};

export const ALARM_PHASE_END = "opentomato-phase-end";
export const ALARM_WARNING = "opentomato-warning";
export const ALARM_BADGE_TICK = "opentomato-badge-tick";

export const PHASE_LABELS = {
  [PHASE.WORK]: "Focus",
  [PHASE.REST]: "Short Break",
  [PHASE.LONG_BREAK]: "Long Break",
};
